name: daily

on:
  #schedule:
  #  - cron: "14 14 * * *"
  # Uncomment below to test.
  push:
    branches: [gha-test-*]

jobs:
  audit:
    runs-on: ubuntu-latest
    container:
      image: diem/build_environment:main
    strategy:
      fail-fast: false
      matrix:
        #this is a painful solution since it doesn't pick up new branches, other option is lotsa shell in one job....
        #to test in canary add in canary here.....
        target-branch: [gha-test-1]
    env:
      AUDIT_SUMMARY_FILE: /tmp/summary
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.target-branch }}
      - uses: ./.github/actions/build-setup
      - name: install cargo-audit
        run: cargo install --force cargo-audit
      - name: audit crates
        # List of ignored RUSTSEC
        # 1. RUSTSEC-2021-0020 - Not impacted, see #7723
        # 2. RUSTSEC-2020-0146 - Not impacted, see #7826
        run: |
          cargo audit -D yanked > $AUDIT_SUMMARY_FILE
      - uses: actions/github-script@v3
        if: ${{ failure() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = `RUSTSEC in dependencies in branch ${{ matrix.target-branch }}`
            const fsp = require('fs').promises
            summary = await fsp.readFile('${{ env.AUDIT_SUMMARY_FILE }}', 'utf-8')
            const job_url = `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            const body = `Found RUSTSEC in dependencies in job ${job_url}
            \`\`\`
            ${summary}
            \`\`\`
            `
            const assignees = [`sausagee`]
            const labels = [`dependencies`]
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/actions/create-issue/action-script.js`)
            await script({github, context, title, body, assignees, labels})
      - uses: ./.github/actions/build-teardown
